import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-currency-flag',
  templateUrl: './currency-flag.component.html',
  styleUrl: './currency-flag.component.css'
})
export class CurrencyFlagComponent {
  @Input() currencyCode: string = '';
  public imageErrors: { [key: string]: boolean } = {};

  private currencyToCountryMap: { [key: string]: string } = {
    'aed': 'AE',
    'afn': 'AF',
    'all': 'AL',
    'amd': 'AM',
    'ang': 'CW',
    'aoa': 'AO',
    'ars': 'AR',
    'aud': 'AU',
    'awg': 'AW',
    'azn': 'AZ',
    'bam': 'BA',
    'bbd': 'BB',
    'bdt': 'BD',
    'bgn': 'BG',
    'bhd': 'BH',
    'bif': 'BI',
    'bmd': 'BM',
    'bnd': 'BN',
    'bob': 'BO',
    'brl': 'BR',
    'bsd': 'BS',
    'btn': 'BT',
    'bwp': 'BW',
    'byn': 'BY',
    'bzd': 'BZ',
    'cad': 'CA',
    'cdf': 'CD',
    'chf': 'CH',
    'clp': 'CL',
    'cny': 'CN',
    'cop': 'CO',
    'crc': 'CR',
    'cup': 'CU',
    'cve': 'CV',
    'czk': 'CZ',
    'djf': 'DJ',
    'dkk': 'DK',
    'dop': 'DO',
    'dzd': 'DZ',
    'egp': 'EG',
    'ern': 'ER',
    'etb': 'ET',
    'eur': 'EU',
    'fjd': 'FJ',
    'fkp': 'FK',
    'fok': 'FO',
    'gbp': 'GB',
    'gel': 'GE',
    'ggp': 'GG',
    'ghs': 'GH',
    'gip': 'GI',
    'gmd': 'GM',
    'gnf': 'GN',
    'gtq': 'GT',
    'gyd': 'GY',
    'hkd': 'HK',
    'hnl': 'HN',
    'hrk': 'HR',
    'htg': 'HT',
    'huf': 'HU',
    'idr': 'ID',
    'ils': 'IL',
    'imp': 'IM',
    'inr': 'IN',
    'iqd': 'IQ',
    'irr': 'IR',
    'isk': 'IS',
    'jep': 'JE',
    'jmd': 'JM',
    'jod': 'JO',
    'jpy': 'JP',
    'kes': 'KE',
    'kgs': 'KG',
    'khr': 'KH',
    'kid': 'KI',
    'kmf': 'KM',
    'krw': 'KR',
    'kwd': 'KW',
    'kyd': 'KY',
    'kzt': 'KZ',
    'lak': 'LA',
    'lbp': 'LB',
    'lkr': 'LK',
    'lrd': 'LR',
    'lsl': 'LS',
    'lyd': 'LY',
    'mad': 'MA',
    'mdl': 'MD',
    'mga': 'MG',
    'mkd': 'MK',
    'mmk': 'MM',
    'mnt': 'MN',
    'mop': 'MO',
    'mru': 'MR',
    'mur': 'MU',
    'mvr': 'MV',
    'mwk': 'MW',
    'mxn': 'MX',
    'myr': 'MY',
    'mzn': 'MZ',
    'nad': 'NA',
    'ngn': 'NG',
    'nio': 'NI',
    'nok': 'NO',
    'npr': 'NP',
    'nzd': 'NZ',
    'omr': 'OM',
    'pab': 'PA',
    'pen': 'PE',
    'pgk': 'PG',
    'php': 'PH',
    'pkr': 'PK',
    'pln': 'PL',
    'pyg': 'PY',
    'qar': 'QA',
    'ron': 'RO',
    'rsd': 'RS',
    'rub': 'RU',
    'rwf': 'RW',
    'sar': 'SA',
    'sbd': 'SB',
    'scr': 'SC',
    'sdg': 'SD',
    'sek': 'SE',
    'sgd': 'SG',
    'shp': 'SH',
    'sll': 'SL',
    'sos': 'SO',
    'srd': 'SR',
    'ssp': 'SS',
    'stn': 'ST',
    'sle': 'SL',
    'syp': 'SY',
    'svc': 'SV',
    'szl': 'SZ',
    'thb': 'TH',
    'tjs': 'TJ',
    'tmt': 'TM',
    'tnd': 'TN',
    'top': 'TO',
    'try': 'TR',
    'ttd': 'TT',
    'tvd': 'TV',
    'twd': 'TW',
    'tzs': 'TZ',
    'uah': 'UA',
    'ugx': 'UG',
    'usd': 'US',
    'uyu': 'UY',
    'uzs': 'UZ',
    'ves': 'VE',
    'vnd': 'VN',
    'vuv': 'VU',
    'wst': 'WS',
    'xaf': 'CF',
    'xcd': 'LC',
    'xof': 'CI',
    'xpf': 'PF',
    'yer': 'YE',
    'zar': 'ZA',
    'zmw': 'ZM',
    'zwl': 'ZW'
  };

  getCountryCode(currencyCode: string): string {
    return this.currencyToCountryMap[currencyCode.toLowerCase()];
  }

  handleImageError(currencyCode: string) {
    this.imageErrors[currencyCode] = true;
  }
}
